<a href="https://colab.research.google.com/github/rsconsuegra/MisionTIC2021/blob/main/Bidimensional.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from typing import List,Tuple

# Diferentes modos de lectura


In [ ]:
def pretty_print(mat: List[List[int]], nf: int, nc:int )-> None:
  """
  Prints a matrix in terminal, in a pretty format. 

  Parameters
  ----------
  mat :  A list of list of integers, asumming 
         all lists are of the same size
  nf  :  Scalar indicating the number of rows
  nc  :  Scalar indicating the number of columns  

  Returns
  -------
    None
  """
  print("La matriz es:")
  for i in range(nf):
    for j in range(nc):
      print(mat[i][j],end=" ")
    print("")

In [ ]:
# Ir agregando elementos directamente con append e indices
A: List[List[int]]= []
nf: int = int(input())
nc: int = int(input())

for i in range(nf):
  A.append([])
  for j in range(nc):
    elemento: int = int(input(f'Ingrese valor en posicion {i}-{j}: '))
    A[i].append(elemento)

pretty_print(A,nf,nc)

3
3
Ingrese valor en posicion 0-0: 4
Ingrese valor en posicion 0-1: 2
Ingrese valor en posicion 0-2: 6
Ingrese valor en posicion 1-0: 9
Ingrese valor en posicion 1-1: 7
Ingrese valor en posicion 1-2: 1
Ingrese valor en posicion 2-0: 2
Ingrese valor en posicion 2-1: 3
Ingrese valor en posicion 2-2: 4
La matriz es:
4 2 6 
9 7 1 
2 3 4 


In [ ]:
# Ir agregando elementos a una lista auxiliar y luego agregarla a la matriz
A: List[List[int]]= []
nf: int = int(input())
nc: int = int(input())

for i in range(nf):
  v: List[int] = []
  for j in range(nc):
    elemento: int = int(input(f'Ingrese valor en posicion {i}-{j}: '))
    v.append(elemento)
  A.append(v)
pretty_print(A,nf,nc)

2
2
Ingrese valor en posicion 0-03
Ingrese valor en posicion 0-14
Ingrese valor en posicion 1-09
Ingrese valor en posicion 1-15
La matriz es:
3 4 

9 5 



In [ ]:
#Inicializando la matriz en 0's (usando list comprehension)
nf: int = int(input())
nc: int = int(input())
A: List[List[int]] = [[0 for j in range(nf)]for i in range(nc)] 

for i in range(nf):
  for j in range(nc):
    elemento: int = int(input(f'Ingrese valor en posicion {i}-{j}: '))
    A[i][j] = elemento

pretty_print(A,nf,nc)

2
2
Ingrese valor en posicion 0-04
Ingrese valor en posicion 0-16
Ingrese valor en posicion 1-07
Ingrese valor en posicion 1-18
La matriz es:
4 6 

7 8 



In [ ]:
#Ir agregando fila por fila, usando un mapeo
A: List[List[int]]= []
nf: int = int(input())
nc: int = int(input())

for i in range(nf):
  elemento: List[int] = list(map(int,input().split()))
  A.append(elemento)
pretty_print(A,nf,nc)

2
2
2 3
4 5
La matriz es:
2 3 
4 5 


# Numeros aleatorios y matrices



In [ ]:
from random import choice
pendiente = [4]
def numAleatorio():
  pendiente.append(choice([i for i in range(1,100) if i not in pendiente]))  

numAleatorio()
print(pendiente)

[4, 53]


In [ ]:
from random import choices

nf: int = 5
nc: int = 10
A: List[List[int]] = []
upper_bound: int = 100

for j in range(nf):
  A.append(choices(range(upper_bound+1), k=nc))
A

[[61, 10, 38, 72, 16, 18, 93, 97, 94, 98],
 [95, 87, 19, 22, 35, 41, 74, 89, 97, 52],
 [44, 56, 28, 80, 93, 73, 54, 1, 66, 29],
 [87, 68, 71, 32, 16, 93, 93, 67, 80, 52],
 [72, 32, 87, 85, 21, 75, 30, 94, 91, 75]]

In [ ]:
def arg_max(mat: List[List[int]])-> Tuple[int,str]:
  list_max: List[int] = max(mat)
  max_item: int = max(list_max)

  i_index: int = mat.index(list_max)
  j_index: int = mat[i_index].index(max_item)
  coordinates: str = f'({i_index},{j_index})'
  return max_item,coordinates

maximum,coord = arg_max(A)
print(f'El maximo es {maximum} y su coordenada es {coord}')

El maximo es 87 y su coordenada es (2,3)


In [ ]:
max_elem = max(max(A))
found = False
for i in range(nf):
  for j in range(nc):
    if A[i][j] == max_elem:
      found = True
      print(f"Las coordenadas son {i},{j}")
      break
  if found:
    break

Las coordenadas son 0,7


In [ ]:
max_elem = max(max(A))
for i in range(nf):
  if max_elem in A[i]:
    j = A[i].index(max_elem)
    print(f"Las coordenadas son {i},{j}")
    break

Las coordenadas son 0,7


In [ ]:
import numpy as np

numpy_v = np.random.randint(low=1,high=100+1, size=(5,10))
print(numpy_v)

[[32 54 86 69 10 44 75 10 59 13]
 [36 58  9 34 59 33  5  4 58 88]
 [54 83 40 57 59 32 52 30  1 63]
 [ 7  3 99 82 46 68 37 88 14 42]
 [44 23 46 27 76  3  8 20 40 43]]


In [ ]:
print(numpy_v.max())
position = np.where(numpy_v==numpy_v.max())
print(f'{position[0][0]},{position[1][0]}')

99
3,2


In [ ]:
print(numpy_v.max())
print(f'{np.unravel_index(numpy_v.argmax(), numpy_v.shape)}')

99
(3, 2)


In [ ]:
np.where(numpy_v==numpy_v.max())

(array([2]), array([3]))

In [ ]:
numpy_v.max()
col = np.argmax(numpy_v,axis=0)
fila = np.argmax(numpy_v,axis=1)
print(f'{fila}-{col}')

[2 2 1]-[1 2 1]


In [ ]:
np.argmax(numpy_v,axis=None)

5

In [ ]:
numpy_v

array([[ 4,  6,  9],
       [ 7,  8, 26],
       [ 4,  9,  4]])

In [ ]:
v = [[1,3,6],[1,2,3],[1,6,9]]
sum = 0
for i in v:
  for j in i:
    sum = sum + j

prom = sum/9
prom

3.5555555555555554

In [ ]:
p = [1,2,6,9]
n = 4
for i in range(4):
  if p[i]>3:
    p[i] = p[i]*2

p

0
1
2
3


[1, 2, 12, 18]